apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: symphony-prod

resources:
  - ../../base
  - ingress.yaml

namePrefix: prod-

images:
  - name: us-central1-docker.pkg.dev/PROJECT_ID/REPOSITORY/symphony
    newTag: prod-latest

patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
  - path: patch-secret.yaml
  - path: patch-cloudsql-proxy.yaml
