apiVersion: v1
kind: ConfigMap
metadata:
  name: symphony-config
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: dev
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRINGDOC_SWAGGER_UI_URL: /openapi.yaml
  SPRINGDOC_SWAGGER_UI_DISABLE_SWAGGER_DEFAULT_URL: "true"
  APP_SECURITY_ENABLED: "false"
  APP_AUTHZ_MODE: allow-all
